// Demo data for the PRIMARY database only (student_management).
// Values are chosen so the MongoDB operator demos return interesting results:
//   CGPA below 8, exactly 8, above 8, exactly 9 and above 9
//   ages below 20, exactly 20 and above 20
//   students from Jaipur, Delhi and other cities
//   Computer Science, Cyber Security and other branches

const SOURCE = 'Demo Seed Data';

export const demoStudents = [
  {
    studentId: 'PCEA24CY002',
    name: 'Aayushi Bansal',
    age: 19,
    email: 'aayushi@example.com',
    phone: '9876543210',
    gender: 'Female',
    branch: 'Cyber Security',
    semester: 5,
    cgpa: 9.0,
    city: 'Jaipur',
    address: 'Jaipur, Rajasthan',
  },
  {
    studentId: 'PCEA24CS014',
    name: 'Rahul Sharma',
    age: 20,
    email: 'rahul.sharma@example.com',
    phone: '9829012345',
    gender: 'Male',
    branch: 'Computer Science',
    semester: 5,
    cgpa: 8.4,
    city: 'Jaipur',
    address: 'Vaishali Nagar, Jaipur, Rajasthan',
  },
  {
    studentId: 'PCEA24CY007',
    name: 'Priya Verma',
    age: 19,
    email: 'priya.verma@example.com',
    phone: '9811023456',
    gender: 'Female',
    branch: 'Cyber Security',
    semester: 5,
    cgpa: 7.6,
    city: 'Delhi',
    address: 'Rohini, New Delhi',
  },
  {
    studentId: 'PCEA23CS021',
    name: 'Arjun Mehta',
    age: 21,
    email: 'arjun.mehta@example.com',
    phone: '9810034567',
    gender: 'Male',
    branch: 'Computer Science',
    semester: 7,
    cgpa: 9.2,
    city: 'Delhi',
    address: 'Dwarka, New Delhi',
  },
  {
    studentId: 'PCEA25IT009',
    name: 'Sneha Gupta',
    age: 18,
    email: 'sneha.gupta@example.com',
    phone: '9784045678',
    gender: 'Female',
    branch: 'Information Technology',
    semester: 3,
    cgpa: 8.0,
    city: 'Jaipur',
    address: 'Mansarovar, Jaipur, Rajasthan',
  },
  {
    studentId: 'PCEA23EC004',
    name: 'Karan Singh',
    age: 22,
    email: 'karan.singh@example.com',
    phone: '9839056789',
    gender: 'Male',
    branch: 'Electronics & Communication',
    semester: 7,
    cgpa: 6.9,
    city: 'Lucknow',
    address: 'Gomti Nagar, Lucknow, Uttar Pradesh',
  },
  {
    studentId: 'PCEA24AI011',
    name: 'Ananya Iyer',
    age: 19,
    email: 'ananya.iyer@example.com',
    phone: '9845067890',
    gender: 'Female',
    branch: 'AI & Data Science',
    semester: 5,
    cgpa: 9.5,
    city: 'Bengaluru',
    address: 'Jayanagar, Bengaluru, Karnataka',
  },
  {
    studentId: 'PCEA25CS032',
    name: 'Rohan Joshi',
    age: 18,
    email: 'rohan.joshi@example.com',
    phone: '9822078901',
    gender: 'Male',
    branch: 'Computer Science',
    semester: 3,
    cgpa: 7.2,
    city: 'Pune',
    address: 'Kothrud, Pune, Maharashtra',
  },
  {
    studentId: 'PCEA24CS008',
    name: 'Ishita Agarwal',
    age: 20,
    email: 'ishita.agarwal@example.com',
    phone: '9829089012',
    gender: 'Female',
    branch: 'Computer Science',
    semester: 5,
    cgpa: 9.0,
    city: 'Jaipur',
    address: 'C-Scheme, Jaipur, Rajasthan',
  },
  {
    studentId: 'PCEA23CY015',
    name: 'Vikram Choudhary',
    age: 21,
    email: 'vikram.choudhary@example.com',
    phone: '9414090123',
    gender: 'Male',
    branch: 'Cyber Security',
    semester: 7,
    cgpa: 8.7,
    city: 'Jodhpur',
    address: 'Shastri Nagar, Jodhpur, Rajasthan',
  },
  {
    studentId: 'PCEA24IT018',
    name: 'Neha Kapoor',
    age: 20,
    email: 'neha.kapoor@example.com',
    phone: '9818101234',
    gender: 'Female',
    branch: 'Information Technology',
    semester: 5,
    cgpa: 7.9,
    city: 'Delhi',
    address: 'Lajpat Nagar, New Delhi',
  },
  {
    studentId: 'PCEA23AI003',
    name: 'Aditya Rao',
    age: 22,
    email: 'aditya.rao@example.com',
    phone: '9849112345',
    gender: 'Male',
    branch: 'AI & Data Science',
    semester: 7,
    cgpa: 8.0,
    city: 'Hyderabad',
    address: 'Kukatpally, Hyderabad, Telangana',
  },
  {
    studentId: 'PCEA25CY006',
    name: 'Pooja Nair',
    age: 18,
    email: 'pooja.nair@example.com',
    phone: '9820123456',
    gender: 'Female',
    branch: 'Cyber Security',
    semester: 3,
    cgpa: 9.3,
    city: 'Mumbai',
    address: 'Andheri West, Mumbai, Maharashtra',
  },
  {
    studentId: 'PCEA23ME010',
    name: 'Manish Yadav',
    age: 23,
    email: 'manish.yadav@example.com',
    phone: '9460134567',
    gender: 'Male',
    branch: 'Mechanical',
    semester: 7,
    cgpa: 6.5,
    city: 'Kota',
    address: 'Talwandi, Kota, Rajasthan',
  },
  {
    studentId: 'PCEA24CY019',
    name: 'Divya Saxena',
    age: 20,
    email: 'divya.saxena@example.com',
    phone: '9871145678',
    gender: 'Female',
    branch: 'Cyber Security',
    semester: 5,
    cgpa: 8.9,
    city: 'Delhi',
    address: 'Saket, New Delhi',
  },
  {
    studentId: 'PCEA25IT021',
    name: 'Harshvardhan Rathore',
    age: 19,
    email: 'harshvardhan.rathore@example.com',
    phone: '9414156789',
    gender: 'Male',
    branch: 'Information Technology',
    semester: 3,
    cgpa: 7.5,
    city: 'Udaipur',
    address: 'Hiran Magri, Udaipur, Rajasthan',
  },
  {
    studentId: 'PCEA24CS027',
    name: 'Kavya Reddy',
    age: 19,
    email: 'kavya.reddy@example.com',
    phone: '9866167890',
    gender: 'Female',
    branch: 'Computer Science',
    semester: 5,
    cgpa: 8.6,
    city: 'Hyderabad',
    address: 'Banjara Hills, Hyderabad, Telangana',
  },
  {
    studentId: 'PCEA23CS005',
    name: 'Siddharth Jain',
    age: 21,
    email: 'siddharth.jain@example.com',
    phone: '9829178901',
    gender: 'Male',
    branch: 'Computer Science',
    semester: 7,
    cgpa: 7.8,
    city: 'Jaipur',
    address: 'Malviya Nagar, Jaipur, Rajasthan',
  },
  {
    studentId: 'PCEA25AI002',
    name: 'Tanvi Deshmukh',
    age: 18,
    email: 'tanvi.deshmukh@example.com',
    phone: '9819189012',
    gender: 'Female',
    branch: 'AI & Data Science',
    semester: 3,
    cgpa: 9.0,
    city: 'Mumbai',
    address: 'Dadar, Mumbai, Maharashtra',
  },
  {
    studentId: 'PCEA23EC017',
    name: 'Aman Khan',
    age: 21,
    email: 'aman.khan@example.com',
    phone: '9891190123',
    gender: 'Male',
    branch: 'Electronics & Communication',
    semester: 7,
    cgpa: 8.2,
    city: 'Delhi',
    address: 'Jamia Nagar, New Delhi',
  },
].map((student) => ({ ...student, createdBy: 'Aayushi', source: SOURCE }));

export const demoCourses = [
  {
    courseId: 'CS301',
    courseName: 'Data Structures and Algorithms',
    courseCode: 'DSA',
    credits: 4,
    faculty: 'Dr. Pooja Khandelwal',
    semester: 3,
    department: 'Computer Science',
  },
  {
    courseId: 'MA301',
    courseName: 'Discrete Mathematics',
    courseCode: 'DM',
    credits: 3,
    faculty: 'Dr. R. K. Agrawal',
    semester: 3,
    department: 'Mathematics',
  },
  {
    courseId: 'IT301',
    courseName: 'Web Technologies',
    courseCode: 'WT',
    credits: 3,
    faculty: 'Prof. Kavita Sharma',
    semester: 3,
    department: 'Information Technology',
  },
  {
    courseId: 'CS501',
    courseName: 'Database Management System',
    courseCode: 'DBMS',
    credits: 4,
    faculty: 'Dr. Sharma',
    semester: 5,
    department: 'Computer Science',
  },
  {
    courseId: 'CS502',
    courseName: 'Operating Systems',
    courseCode: 'OS',
    credits: 4,
    faculty: 'Dr. Meena Joshi',
    semester: 5,
    department: 'Computer Science',
  },
  {
    courseId: 'CS503',
    courseName: 'Computer Networks',
    courseCode: 'CN',
    credits: 3,
    faculty: 'Prof. Rajesh Gupta',
    semester: 5,
    department: 'Computer Science',
  },
  {
    courseId: 'CY501',
    courseName: 'Cryptography and Network Security',
    courseCode: 'CNS',
    credits: 4,
    faculty: 'Dr. Anjali Mathur',
    semester: 5,
    department: 'Cyber Security',
  },
  {
    courseId: 'CY502',
    courseName: 'Ethical Hacking',
    courseCode: 'EH',
    credits: 3,
    faculty: 'Prof. Vivek Tiwari',
    semester: 5,
    department: 'Cyber Security',
  },
  {
    courseId: 'CY701',
    courseName: 'Digital Forensics',
    courseCode: 'DF',
    credits: 3,
    faculty: 'Dr. Neeraj Saini',
    semester: 7,
    department: 'Cyber Security',
  },
  {
    courseId: 'CS701',
    courseName: 'Machine Learning',
    courseCode: 'ML',
    credits: 4,
    faculty: 'Dr. Sanjay Verma',
    semester: 7,
    department: 'Computer Science',
  },
];

// [studentId, courseId, totalClasses, attendedClasses]
// The percentage and course name are filled in by the seed script / schema.
const attendanceRows = [
  // Semester 5
  ['PCEA24CY002', 'CS501', 40, 35],
  ['PCEA24CY002', 'CY501', 36, 33],
  ['PCEA24CS014', 'CS501', 40, 32],
  ['PCEA24CS014', 'CS502', 38, 30],
  ['PCEA24CY007', 'CS501', 40, 27],
  ['PCEA24CY007', 'CY501', 36, 26],
  ['PCEA24AI011', 'CS501', 40, 39],
  ['PCEA24AI011', 'CS502', 38, 36],
  ['PCEA24CS008', 'CS501', 40, 37],
  ['PCEA24CS008', 'CS502', 38, 34],
  ['PCEA24IT018', 'CS501', 40, 29],
  ['PCEA24IT018', 'CS502', 38, 31],
  ['PCEA24CY019', 'CS501', 40, 34],
  ['PCEA24CY019', 'CY501', 36, 32],
  ['PCEA24CS027', 'CS501', 40, 36],
  ['PCEA24CS027', 'CS502', 38, 33],
  // Semester 7
  ['PCEA23CS021', 'CS701', 34, 31],
  ['PCEA23EC004', 'CS701', 34, 22],
  ['PCEA23CY015', 'CY701', 32, 29],
  ['PCEA23AI003', 'CS701', 34, 30],
  ['PCEA23ME010', 'CS701', 34, 21],
  ['PCEA23CS005', 'CS701', 34, 27],
  ['PCEA23EC017', 'CY701', 32, 25],
  // Semester 3
  ['PCEA25IT009', 'CS301', 42, 38],
  ['PCEA25IT009', 'MA301', 30, 27],
  ['PCEA25CS032', 'CS301', 42, 28],
  ['PCEA25CS032', 'MA301', 30, 21],
  ['PCEA25CY006', 'CS301', 42, 41],
  ['PCEA25IT021', 'CS301', 42, 33],
  ['PCEA25AI002', 'CS301', 42, 40],
  ['PCEA25AI002', 'MA301', 30, 29],
];

export const demoAttendance = attendanceRows.map(([studentId, courseId, totalClasses, attendedClasses]) => ({
  studentId,
  courseId,
  courseName: demoCourses.find((course) => course.courseId === courseId).courseName,
  totalClasses,
  attendedClasses,
}));
